### ISSUE TITLE
Can´t locate IInjector .net 6

### ISSUE THREAD

**Issue by Pavesi99** [ipjohnson/Grace#293]
I have this function: 

 public static IServiceProvider BuildGraceServiceProvider(this IServiceCollection services)
        {
            services.NotifyOnBeforeCreateContainer();
            var onBeforeCreateContainerHandlers = services.GetAllOnBeforeCreateContainerHandlers();

            var container = GraceFactory.ConfigureContainer();
            container.ConfigureService(services);

            var injector = container.Locate<IInjector>();

            onBeforeCreateContainerHandlers.Each(h => h.Invoke(injector));

            return injector;
        }
        
but when I call container.Locate<IInjector>() it throw this error: "Entry point was not found."

with this stack trace(): 
   at Grace.DependencyInjection.Impl.BaseExportLocatorScope.GetOrCreateScopedService[T](Int32 id, ActivationStrategyDelegate createDelegate, IInjectionContext context)
   at Grace.DependencyInjection.Impl.InjectionScope.InternalLocate(IExportLocatorScope scope, IDisposalScope disposalScope, Type type, ActivationStrategyFilter consider, Object key, IInjectionContext injectionContext, Boolean allowNull, Boolean isDynamic)
   at Grace.DependencyInjection.Impl.InjectionScope.Grace.DependencyInjection.IInjectionScope.LocateFromChildScope(IExportLocatorScope childScope, IDisposalScope disposalScope, Type type, Object extraData, ActivationStrategyFilter consider, Object key, Boolean allowNull, Boolean isDynamic)
   at Grace.DependencyInjection.Impl.ActivationStrategyDelegateCache.FallbackExecution(ImmutableHashTree`2 currentNode, Type type, IExportLocatorScope scope, Boolean allowNull, IInjectionContext context)
   at Grace.DependencyInjection.Impl.ActivationStrategyDelegateCache.ExecuteActivationStrategyDelegate(Type type, IExportLocatorScope scope)
   at Grace.DependencyInjection.Impl.BaseExportLocatorScope.Locate(Type type)
   at Grace.DependencyInjection.Impl.BaseExportLocatorScope.Locate[T]()
   at Microsoft.Extensions.DependencyInjection.GraceServiceCollectionExtensions.BuildGraceServiceProvider(IServiceCollection services) 
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

It´s my first contact with Grace, I don´t know what is wrong..

**Comment by ipjohnson** [comment]
Looking at the [release notes](https://github.com/ipjohnson/Grace/wiki/Release-Notes) I don't see any major changes between 7.0 -> 7.1.  

What versions do you have of Grace and the hosting library?

**Comment by Pavesi99** [comment]
I didn't look deep on my code to see what broke, I installed version 7.0 again and it´s work.

Thanks @eglauko and @ipjohnson
