### ISSUE TITLE
Unhelpful error message when registering types

### ISSUE THREAD

**Issue by davidkeaveny** [ipjohnson/Grace#30]
I am using the fluent configuration in an ASP.NET WebForms application to register a number of types from multiple assemblies, something like this:

```csharp
var container = new DependencyInjectionContainer();
container.Configure(grace =>
                    {
                        grace.Register(path);
                   });
```

where `.Register(string)` is an extension method that I've added that uses `Types.FromDirectory` to scan for a particular set of assemblies. When the configure block runs, it throw the following error:

```
System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=Expression of type 'System.Nullable`1[System.Decimal]' cannot be used for assignment to type 'System.Object'
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
       at Grace.DependencyInjection.Impl.CompiledExport.BaseCompiledExportDelegate.ImportFromRequestingScope(Type importType, IInjectionTargetInfo targetInfo, String exportName, ParameterExpression importVariable, Boolean isRequired, ILocateKeyValueProvider locateKey, List`1 expressionList)
       at Grace.DependencyInjection.Impl.CompiledExport.BaseCompiledExportDelegate.CreateImportExpression(Type importType, IInjectionTargetInfo targetInfo, ExportStrategyDependencyType dependencyType, String exportName, String variableName, Boolean isRequired, IExportValueProvider valueProvider, ExportStrategyFilter exportStrategyFilter, ILocateKeyValueProvider locateKey, Object comparerObject, List`1 expressionList)
       at Grace.DependencyInjection.Impl.CompiledExport.InstanceCompiledExportDelegate.CustomConstructorEnrichmentLinqExpressionContext.GetConstructorExpression(ConstructorInfo& constructorInfo, IEnumerable`1& constructorParameters)
       at Grace.DependencyInjection.Impl.CompiledExport.InstanceCompiledExportDelegate.CreateInstantiationExpression()
       at Grace.DependencyInjection.Impl.CompiledExport.BaseCompiledExportDelegate.GenerateDelegate()
       at Grace.DependencyInjection.Impl.CompiledExport.BaseCompiledExportDelegate.CompileDelegate()
       at Grace.DependencyInjection.Impl.CompiledInstanceExportStrategy.Initialize()
       at Grace.DependencyInjection.Impl.AttributeExportStrategy.Initialize()
       at Grace.DependencyInjection.Impl.InjectionKernel.Configure(ExportRegistrationDelegate registrationDelegate)
       at Grace.DependencyInjection.DependencyInjectionContainer.Configure(ExportRegistrationDelegate registrationDelegate)
       at MyProject.Web.Initialisation.InitialiseContainer() in d:\Dev\MyProject\branches\TD-45-remove-unity\WebApplication\Initialisation.Unity.cs:line 26
       at MyProject.Web.Initialisation.Initialise() in d:\Dev\MyProject\branches\TD-45-remove-unity\WebApplication\Initialisation.cs:line 13
  InnerException: 
```

I've used identical registration code in other web projects without any problem, which suggests that there must be some type specific to this project which is being auto-registered that is causing the error, but Grace isn't supplying enough information for me to be able to diagnose what it is. The possibility also exists that it is an actual bug in Grace.

Any suggestions as to what I can do to resolve this? As the stacktrace suggests, I am trying to replace Unity with Grace, and this is the (hopefully) final stumbling block on the path to the Promised Land.

**Comment by ipjohnson** [comment]
Hi David,

Sorry that Grace didn't provide enough debugging information. It does a good job of returning a good message when requesting types but not very good when the error happens in a registration block.

That being said I think something is going wrong with trying to inject a nullable int or something around that (not totally sure). Either way I wouldn't think it should fail like that.

Would it be possible to zip up a copy and send it along, I don't need the app to be able to run merely just start up the app. If not maybe we can figure something else out.

Email me directly if you want ipjohnson123 at yahoo.com

**Comment by ipjohnson** [comment]
I never heard back about this issue so I'm marking it as closed
